# Generated by Django 3.1.3 on 2020-11-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('portion_desc', models.CharField(max_length=50)),
                ('portion_grams', models.IntegerField()),
                ('alternatives', models.CharField(max_length=200)),
                ('ox_per_100g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('source_notes', models.TextField()),
            ],
        ),
    ]
