# Generated by Django 3.1.3 on 2020-11-19 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('portion_desc', models.CharField(max_length=50)),
                ('alternatives', models.CharField(max_length=200)),
                ('source_notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MealIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ing_qty_in_g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup.ingredient')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lookup.meal')),
            ],
        ),
    ]
