# Generated by Django 3.1.3 on 2020-11-23 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0002_meal_mealingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='source_notes',
            new_name='sources',
        ),
    ]
