# Generated by Django 3.1.3 on 2021-01-16 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0003_auto_20201123_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealingredient',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup.meal'),
        ),
    ]
